#define API_KEY "AIzaSyD9FWJKrJF7q93V1H0V0vdk8jVjD2Dr6CI"
#define STA_SSID "Livebox-bibou"
#define STA_PASSWORD "camilleyoann_3457"
#define USER_EMAIL "test@gmail.com"
#define USER_PASSWORD "test34"
#define FIREBASE_PROJECT_ID "iotprojectdatabase"
#define ROOM_LOCATION_ID "8xGBtIdog1Nl9N47Zh4I"