#define API_KEY "AIzaSyD9FWJKrJF7q93V1H0V0vdk8jVjD2Dr6CI"
#define USER_EMAIL "test@gmail.com"
#define USER_PASSWORD "test34"
#define FIREBASE_PROJECT_ID "iotprojectdatabase"
#define ROOM_LOCATION_ID "8xGBtIdog1Nl9N47Zh4I"
#define ESP_NAME_CONNEXION "ESP32-Yoann-Sandratra"
